name: api-build

on:
  push:
    paths:
      - ".github/workflows/api-build.yml"
      - "api/**"
  workflow_dispatch: # manual dispatch for the workflow

jobs:
  build:
    name: build-dotnet-api
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - run: |
          dotnet --list-runtimes
          dotnet --list-sdks
          dotnet build
        working-directory: ./api

          