name: cd-azure

on:
  push:
    paths:
      - '.github/workflows/cd-azure.yml'
      - 'api/**'
  workflow_dispatch: #manual dispatch


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # all commits, so we can generate the version from tags/commits
      - uses: docker/setup-buildx-action@v3
      - run: docker buildx ls
      - uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: ./build-push.sh # can reuse local build scripts for CI/CD