name: upper-build

on:
  push:
    paths:
      - ".github/workflows/upper-build.yml"
      - "upper/**"
  workflow_dispatch:

jobs:
  build:
    name: build-go-upper
    runs-on: 
    steps:
      - run: pwd && ls -al
      - name: checkout code
        uses: actions/checkout@v4
      - run: pwd && ls -al
      - run: go version 
      - uses: actions/setup-go@v5
        with:
          # go-version: '1.22'
          go-version-file: ./upper/go.mod
          cache-dependency-path: ./upper/go.sum
      - run: go mod download
        working-directory: ./upper
      - name: build and test
        run: |
          ls
          go build
          ls
          go test
          ./upper foo the bar
        working-directory: ./upper

