name: upper-build

on:
  push:
    paths:
      - ".github/workflows/upper-build.yml"
      - "upper/**"
  workflow_dispatch:

jobs:
  build:
    name: build-go-upper
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - run: |
          go version 
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - run: go build
        working-directory: ./upper

