name: upper-image

on:
  push:
    paths:
      - '.github/workflows/upper-image.yml'
      - 'upper/**'
    workflow_dispatch:


permissions:
    packages: write
    contents: read

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker version
      - run: docker build -t upper .
        working-directory: ./upper
      - name: test it
        run: docker container run upper hello timos
      - uses: actions/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker tag upper ghcr.io/efthymios-stathakis/upper:latest
      - run: docker tag upper ghcr.io/efthymios-stathakis/upper:${{ github.ref_name}}
      - run: docker push ghcr.io/efthymios-stathakis/upper:latest
      - run: docker push ghcr.io/efthymios-stathakis/upper:${{ github.ref_name}}